In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [4]:
data=pd.read_csv(r"C:\Users\PHANEENDRA\Downloads\data_clean.csv")
data

Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [6]:
data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [8]:
data["Temp C"].unique()

array(['67', '72', '74', '62', '56', '66', '65', '59', '61', '69', 'C',
       '68', '58', '64', '57', '73', '81', '79', '76', '78', '84', '85',
       '82', '87', '90', '93', '92', '80', '77', '75', '83', '88', '89',
       '91', '86', '97', '94', '96', '71', '63', '70'], dtype=object)

In [20]:
data["Temp C"]=pd.to_numeric(data["Temp C"], errors="coerce")
data["Temp C"]=data["Temp C"].astype("int64")
data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C          int64
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [22]:
data["Temp C"]=data["Temp C"].fillna(data["Temp C"].mean())
data["Temp C"].unique()

array([67, 72, 74, 62, 56, 66, 65, 59, 61, 69, 77, 68, 58, 64, 57, 73, 81,
       79, 76, 78, 84, 85, 82, 87, 90, 93, 92, 80, 75, 83, 88, 89, 91, 86,
       97, 94, 96, 71, 63, 70], dtype=int64)

In [38]:
data['Month']=data['Month'].replace('May',5)
data["Month"]=data['Month'].astype("int64")
data["Month"].unique()

array([5, 6, 7, 8, 9], dtype=int64)

In [40]:
data.columns

Index(['Unnamed: 0', 'Ozone', 'Solar.R', 'Wind', 'Temp C', 'Month', 'Day',
       'Year', 'Temp', 'Weather'],
      dtype='object')

In [42]:
data['Ozone'].unique()

array([ 41.,  36.,  12.,  18.,  nan,  28.,  23.,  19.,   8.,   7.,  16.,
        11.,  14.,  34.,   6.,  30.,   1.,   4.,  32.,  45., 115.,  37.,
        29.,  71.,  39.,  21.,  20.,  13., 135.,  49.,  64.,  40.,  77.,
        97.,  85.,  10.,  27.,  48.,  35.,  61.,  79.,  63.,  80., 108.,
        52.,  82.,  50.,  59.,   9.,  78.,  66., 122.,  89., 110.,  44.,
        65.,  22.,  31., 168.,  73.,  76., 118.,  84.,  96.,  91.,  47.,
        24.,  46.])

In [44]:
data.isnull().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [52]:
data['Ozone']=data['Ozone'].fillna(data['Ozone'].mean())
data['Ozone']=data['Ozone'].astype("int64")
data.isnull().sum()

Unnamed: 0    0
Ozone         0
Solar.R       7
Wind          0
Temp C        0
Month         0
Day           0
Year          0
Temp          0
Weather       3
dtype: int64

In [54]:
data['Solar.R'].unique()

array([190., 118., 149., 313.,  nan, 299.,  99.,  19., 194., 256., 290.,
       274.,  65., 334., 307.,  78., 322.,  44.,   8., 320.,  25.,  92.,
        66., 266.,  13., 252., 223., 279., 286., 287., 242., 186., 220.,
       264., 127., 273., 291., 323., 259., 250., 148., 332., 191., 284.,
        37., 120., 137., 150.,  59.,  91., 135.,  47.,  98.,  31., 138.,
       269., 248., 236., 101., 175., 314., 276., 267., 272., 139.,  48.,
       260., 285., 187.,   7., 258., 295., 294.,  81.,  82., 213., 275.,
       253., 254.,  83.,  24.,  77., 255., 229., 207., 222., 192., 157.,
        64.,  71.,  51., 115., 244.,  36., 212., 238., 215., 153., 203.,
       225., 237., 188., 167., 197., 183., 189.,  95., 230., 112., 224.,
        27., 201.,  14.,  49.,  20., 193., 145., 131.])

In [56]:
data['Solar.R']=data['Solar.R'].fillna(data['Solar.R'].mean())
data['Solar.R']=data['Solar.R'].astype("int64")
data.isnull().sum()

Unnamed: 0    0
Ozone         0
Solar.R       0
Wind          0
Temp C        0
Month         0
Day           0
Year          0
Temp          0
Weather       3
dtype: int64

In [58]:
data["Weather"].unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [60]:
data["Weather"].value_counts()

Weather
S     59
C     49
PS    47
Name: count, dtype: int64

In [62]:
data["Weather"].isnull().sum()

3

In [64]:
data['Weather']=data["Weather"].fillna(data["Weather"].mode()[0])
data["Weather"].isnull().sum()

0

In [66]:
data["Weather"].unique()

array(['S', 'C', 'PS'], dtype=object)

In [16]:
data.isnull().sum()

Unnamed: 0    0
Ozone         0
Solar.R       0
Wind          0
Temp C        0
Month         0
Day           0
Year          0
Temp          0
Weather       0
dtype: int64

In [68]:
data.dtypes

Unnamed: 0      int64
Ozone           int64
Solar.R         int64
Wind          float64
Temp C          int64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

**Solve the qns**

In [74]:
data.columns

Index(['Unnamed: 0', 'Ozone', 'Solar.R', 'Wind', 'Temp C', 'Month', 'Day',
       'Year', 'Temp', 'Weather'],
      dtype='object')

In [76]:
data.shape

(158, 10)

In [78]:
data.dtypes

Unnamed: 0      int64
Ozone           int64
Solar.R         int64
Wind          float64
Temp C          int64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [80]:
data.head()

Unnamed: 0  Ozone  Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
0           1     41      190   7.4      67      5    1  2010    67       S
1           2     36      118   8.0      72      5    2  2010    72       C
2           3     12      149  12.6      74      5    3  2010    74      PS
3           4     18      313  11.5      62      5    4  2010    62       S
4           5     41      185  14.3      56      5    5  2010    56       S

**1.Find out the the days which has temp value below 70 and high ozone which is > 40**

In [125]:
indices=data[(data["Temp C"] < 70) & (data["Ozone"] > 40)].index
data.loc[indices]

Unnamed: 0  Ozone  Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
0             1     41      190   7.4      67      5    1  2010    67       S
4             5     41      185  14.3      56      5    5  2010    56       S
9            10     41      194   8.6      69      5   10  2010    69       S
24           25     41       66  16.6      57      5   25  2010    57      PS
25           26     41      266  14.9      58      5   26  2010    58       C
26           27     41      185   8.0      57      5   27  2010    57      PS
33           34     41      242  16.1      67      6    3  2010    67      PS
153         154     41      190   7.4      67      5    1  2010    67       C

**2.Extract the temperature of month 6**

In [88]:
data1=data[data["Month"]==6][["Month","Temp"]]
data1
# indices1=data1.groupby("Temp C")["Month"].apply(lambda x:x==6.0).index
# data.loc[indices1]
# temp=data1.groupby("Month")["Temp C"]
# temp

Month  Temp
31      6    78
32      6    74
33      6    67
34      6    84
35      6    85
36      6    79
37      6    82
38      6    87
39      6    90
40      6    87
41      6    93
42      6    92
43      6    82
44      6    80
45      6    79
46      6    77
47      6    72
48      6    65
49      6    73
50      6    76
51      6    77
52      6    76
53      6    76
54      6    76
55      6    75
56      6    78
57      6    73
58      6    80
59      6    77
60      6    83

**3.Find out the average temperature of month 5**

In [93]:
data["Temp C"].unique()

array([67, 72, 74, 62, 56, 66, 65, 59, 61, 69, 77, 68, 58, 64, 57, 73, 81,
       79, 76, 78, 84, 85, 82, 87, 90, 93, 92, 80, 75, 83, 88, 89, 91, 86,
       97, 94, 96, 71, 63, 70], dtype=int64)

In [100]:
avg_temp=data.groupby("Month")["Temp C"].mean()
avg_temp

Month
5    65.687500
6    79.100000
7    83.903226
8    83.967742
9    76.617647
Name: Temp C, dtype: float64

In [102]:
avg_temp[5]

65.6875

**4.Try sorting the wind column**

In [105]:
data.sort_values(by="Wind",ascending=True,inplace=False)

Unnamed: 0  Ozone  Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
52           53     41       59   1.7      76      6   22  2010    76       C
120         121    118      225   2.3      94      8   29  2010    94       S
125         126     73      183   2.8      93      9    3  2010    93       C
116         117    168      238   3.4      81      8   25  2010    81      PS
98           99    122      255   4.0      89      8    7  2010    89       C
..          ...    ...      ...   ...     ...    ...  ...   ...   ...     ...
24           25     41       66  16.6      57      5   25  2010    57      PS
21           22     11      320  16.6      73      5   22  2010    73       C
17           18      6       78  18.4      57      5   18  2010    57       C
8             9      8       19  20.1      61      5    9  2010    61      PS
47           48     37      284  20.7      72      6   17  2010    72       C

[158 rows x 10 columns]

**5.Find out which is hottest temperature and coldest temperature.**

In [143]:
# high_temp=data.sort_values(by="Temp C",ascending=False,inplace=False)
high_temp=data['Temp C'].idxmax()
# data.iloc[high_temp:high_temp+1
low_temp=data['Temp C'].idxmin()
# data.iloc[low_temp:low_temp+1]
data.loc[[high_temp,low_temp]]

Unnamed: 0  Ozone  Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
119         120     76      203   9.7      97      8   28  2010    97       S
4             5     41      185  14.3      56      5    5  2010    56       S