In [173]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)

In [175]:
df=pd.read_csv(r"C:\Users\PHANEENDRA\Downloads\Automobile_data.csv")
df

index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc   
1       1  alfa-romero  convertible        88.6   168.8        dohc   
2       2  alfa-romero    hatchback        94.5   171.2        ohcv   
3       3         audi        sedan        99.8   176.6         ohc   
4       4         audi        sedan        99.4   176.6         ohc   
..    ...          ...          ...         ...     ...         ...   
56     81   volkswagen        sedan        97.3   171.7         ohc   
57     82   volkswagen        sedan        97.3   171.7         ohc   
58     86   volkswagen        sedan        97.3   171.7         ohc   
59     87        volvo        sedan       104.3   188.8         ohc   
60     88        volvo        wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
0              four         111               21  13495.0  
1              four         111               21  16500.0  
2               six         154               19  16500.0  
3              four         102               24  13950.0  
4              five         115               18  17450.0  
..              ...         ...              ...      ...  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0  

[61 rows x 10 columns]

In [6]:
df.drop('index',axis=1,inplace=True)

In [10]:
df.shape

(61, 9)

In [14]:
df.dtypes

company              object
body-style           object
wheel-base          float64
length              float64
engine-type          object
num-of-cylinders     object
horsepower            int64
average-mileage       int64
price               float64
dtype: object

## Exercise 1

Exercise 1: Clean the dataset and update the CSV file    
Replace all column values that contain ‘?’, ‘n.a’, or ‘NaN’.

In [16]:
df['company'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mitsubishi',
       'nissan', 'porsche', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [24]:
df['company'].value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64

In [18]:
df['body-style'].unique()

array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object)

In [26]:
df['company'].value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64

In [20]:
df['wheel-base'].unique()

array([ 88.6,  94.5,  99.8,  99.4, 105.8, 101.2, 103.5, 110. ,  88.4,
        93.7,  96.5,  94.3, 113. , 102. ,  93.1,  95.3, 104.9, 120.9,
       112. ,  96.3, 100.4,  89.5,  98.4,  95.7, 104.5,  97.3, 104.3])

In [28]:
df['wheel-base'].value_counts()

wheel-base
94.5     9
95.7     6
97.3     4
93.7     4
101.2    3
110.0    3
93.1     3
96.5     3
88.6     2
113.0    2
89.5     2
96.3     2
104.3    2
103.5    2
99.8     2
94.3     1
88.4     1
95.3     1
104.9    1
120.9    1
112.0    1
100.4    1
105.8    1
98.4     1
99.4     1
104.5    1
102.0    1
Name: count, dtype: int64

In [30]:
df['length'].unique()

array([168.8, 171.2, 176.6, 177.3, 192.7, 176.8, 189. , 193.8, 197. ,
       141.1, 155.9, 158.8, 157.3, 157.1, 175.4, 169.1, 170.7, 199.6,
       191.7, 159.1, 169. , 175. , 190.9, 208.1, 199.2, 172.4, 165.3,
       170.2, 184.6, 168.9, 175.7, 158.7, 169.7, 187.8, 171.7, 188.8])

In [32]:
df['length'].value_counts()

length
171.7    4
157.3    4
169.7    3
158.7    3
176.8    3
165.3    3
155.9    3
159.1    3
168.8    2
199.6    2
168.9    2
172.4    2
190.9    2
188.8    2
176.6    2
175.4    1
169.1    1
187.8    1
177.3    1
192.7    1
175.7    1
189.0    1
184.6    1
170.2    1
193.8    1
197.0    1
199.2    1
208.1    1
141.1    1
175.0    1
169.0    1
158.8    1
171.2    1
157.1    1
170.7    1
191.7    1
Name: count, dtype: int64

In [34]:
df['engine-type'].unique()

array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'], dtype=object)

In [36]:
df['engine-type'].value_counts()

engine-type
ohc      46
dohc      5
ohcv      5
ohcf      2
l         1
rotor     1
dohcv     1
Name: count, dtype: int64

In [38]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [42]:
df['num-of-cylinders'].value_counts()

num-of-cylinders
four      39
six       11
five       5
eight      3
three      1
twelve     1
two        1
Name: count, dtype: int64

In [44]:
df['horsepower'].unique()

array([111, 154, 102, 115, 110, 101, 121, 182,  48,  70,  68,  76, 100,
        78, 176, 262,  72, 123, 184,  88,  55,  69, 152, 207, 288,  62,
       156,  52,  85, 114], dtype=int64)

In [46]:
df['horsepower'].value_counts()

horsepower
68     7
62     6
101    4
70     4
69     3
182    3
111    2
176    2
52     2
207    2
88     2
184    2
123    2
114    2
100    2
110    2
78     1
154    1
72     1
76     1
48     1
55     1
121    1
152    1
288    1
115    1
156    1
102    1
85     1
262    1
Name: count, dtype: int64

In [50]:
df['average-mileage'].unique()

array([21, 19, 24, 18, 23, 16, 15, 47, 38, 31, 30, 25, 13, 17, 22, 14, 37,
       45, 35, 27, 26], dtype=int64)

In [52]:
df['average-mileage'].value_counts()

average-mileage
31    12
19     5
17     4
23     4
38     4
21     3
24     3
27     3
37     3
15     3
25     3
14     2
22     2
30     2
16     2
13     1
47     1
45     1
35     1
18     1
26     1
Name: count, dtype: int64

In [48]:
df.isnull().sum()

company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               3
dtype: int64

In [54]:
df['price'].unique()

array([13495., 16500., 13950., 17450., 15250., 18920., 16430., 16925.,
       20970., 30760., 41315., 36880.,  5151.,  6295.,  6575.,  6377.,
        6229.,  7295., 12945., 10345.,  6785.,    nan, 32250., 35550.,
       36000.,  5195.,  6095.,  6795., 11845., 18344., 25552., 28248.,
       40960., 45400.,  5389.,  6189.,  6989.,  8189.,  7099.,  6649.,
        6849.,  7349., 13499., 34028., 37028.,  5348.,  6338.,  6488.,
        6918.,  7898.,  8778., 15750.,  7775.,  7975.,  7995.,  9995.,
       12940., 13415.])

In [56]:
df['price'].dtype

dtype('float64')

In [60]:
df['price'].isnull().sum()

3

In [62]:
df['price']=df['price'].fillna(df['price'].mean())

In [64]:
df['price'].unique()

array([13495., 16500., 13950., 17450., 15250., 18920., 16430., 16925.,
       20970., 30760., 41315., 36880.,  5151.,  6295.,  6575.,  6377.,
        6229.,  7295., 12945., 10345.,  6785., 15387., 32250., 35550.,
       36000.,  5195.,  6095.,  6795., 11845., 18344., 25552., 28248.,
       40960., 45400.,  5389.,  6189.,  6989.,  8189.,  7099.,  6649.,
        6849.,  7349., 13499., 34028., 37028.,  5348.,  6338.,  6488.,
        6918.,  7898.,  8778., 15750.,  7775.,  7975.,  7995.,  9995.,
       12940., 13415.])

In [66]:
df['price'].isnull().sum()

0

## Exercise 2: 
Find the most expensive car company name    
Print the name and price of the most expensive car company.

In [72]:
most_exp_car_index=df['price'].idxmax()
most_exp_car_index

35

In [100]:
df.loc[35:35,['company','price']]

company    price
35  mercedes-benz  45400.0

In [135]:
df.groupby('company')['price'].max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu            15387.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

## Exercise 3: 
Print All Toyota Cars details

In [107]:
df1=df[df['company']=='toyota']
df1

company body-style  wheel-base  length engine-type num-of-cylinders  \
48  toyota  hatchback        95.7   158.7         ohc             four   
49  toyota  hatchback        95.7   158.7         ohc             four   
50  toyota  hatchback        95.7   158.7         ohc             four   
51  toyota      wagon        95.7   169.7         ohc             four   
52  toyota      wagon        95.7   169.7         ohc             four   
53  toyota      wagon        95.7   169.7         ohc             four   
54  toyota      wagon       104.5   187.8        dohc              six   

    horsepower  average-mileage    price  
48          62               35   5348.0  
49          62               31   6338.0  
50          62               31   6488.0  
51          62               31   6918.0  
52          62               27   7898.0  
53          62               27   8778.0  
54         156               19  15750.0

## Exercise 4: 
Count total cars per company

In [114]:
df2=df['company'].value_counts()
df2

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64

## Exercise 5: 
Find the average mileage of each car making company

In [121]:
df3=df.groupby('company')['average-mileage'].mean()
pd.DataFrame(df3)

average-mileage
company                       
alfa-romero          20.333333
audi                 20.000000
bmw                  19.000000
chevrolet            41.000000
dodge                31.000000
honda                26.333333
isuzu                33.333333
jaguar               14.333333
mazda                28.000000
mercedes-benz        18.000000
mitsubishi           29.500000
nissan               31.400000
porsche              17.000000
toyota               28.714286
volkswagen           31.750000
volvo                23.000000

## Exercise 6: 
Sort all cars by Price column

In [132]:
df4=df.sort_values(by='price', ascending=False,inplace=False)
df4.head()

company   body-style  wheel-base  length engine-type  \
35  mercedes-benz      hardtop       112.0   199.2        ohcv   
11            bmw        sedan       103.5   193.8         ohc   
34  mercedes-benz        sedan       120.9   208.1        ohcv   
46        porsche  convertible        89.5   168.9        ohcf   
12            bmw        sedan       110.0   197.0         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight         184               14  45400.0  
11              six         182               16  41315.0  
34            eight         184               14  40960.0  
46              six         207               17  37028.0  
12              six         182               15  36880.0

## Exercise 7: 
Concatenate two data frames using the following conditions    


In [ ]:
Create two data frames using the following two dictionaries.
GermanCars = {'Company': [Ford, Mercedes, BMV, Audi], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi'], 'Price': [29995, 23600, 61500 , 58900]}

In [142]:
GermanCars = pd.DataFrame({'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]})
japaneseCars = pd.DataFrame({'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi'], 'Price': [29995, 23600, 61500 , 58900]})

In [152]:
df=pd.concat([GermanCars, japaneseCars],keys=['German','Japanese'])
df

Company   Price
German   0        Ford   23845
         1    Mercedes  171995
         2         BMV  135925
         3        Audi   71400
Japanese 0      Toyota   29995
         1       Honda   23600
         2      Nissan   61500
         3  Mitsubishi   58900

## Exercise 8: 
Merge two data frames using the following condition 

Create two data frames using the following two Dicts, Merge two data frames, and append the second data frame as a new column to the first data frame.   
Car_Price = {'Company':['Toyota','Honda','BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}    
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141,80,182,160]}

In [162]:
Car_Price = pd.DataFrame({'Company':['Toyota','Honda','BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]})  
car_Horsepower = pd.DataFrame({'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141,80,182,160]})

In [170]:
df=pd.merge(Car_Price,car_Horsepower,how='outer')
df

Company   Price  horsepower
0    Audi   71400         160
1     BMV  135925         182
2   Honda   17995          80
3  Toyota   23845         141

## xtras

In [177]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [179]:
dictMap={'four':4, 'six':6, 'five':5, 'three':3, 'twelve':12, 'two':2, 'eight':8}

In [181]:
df['num-of-cylinders']=df['num-of-cylinders'].map(dictMap)

In [183]:
df.sample(10)

index        company body-style  wheel-base  length engine-type  \
11     14            bmw      sedan       103.5   193.8         ohc   
8      10            bmw      sedan       101.2   176.8         ohc   
5       5           audi      sedan        99.8   177.3         ohc   
15     18      chevrolet      sedan        94.5   158.8         ohc   
53     71         toyota      wagon        95.7   169.7         ohc   
32     44  mercedes-benz      sedan       110.0   190.9         ohc   
19     28          honda      sedan        96.5   175.4         ohc   
3       3           audi      sedan        99.8   176.6         ohc   
7       9            bmw      sedan       101.2   176.8         ohc   
25     34         jaguar      sedan       113.0   199.6        dohc   

    num-of-cylinders  horsepower  average-mileage    price  
11                 6         182               16  41315.0  
8                  4         101               23  16925.0  
5                  5         110               19  15250.0  
15                 4          70               38   6575.0  
53                 4          62               27   8778.0  
32                 5         123               22  25552.0  
19                 4         101               24  12945.0  
3                  4         102               24  13950.0  
7                  4         101               23  16430.0  
25                 6         176               15  35550.0

In [185]:
df.dtypes

index                 int64
company              object
body-style           object
wheel-base          float64
length              float64
engine-type          object
num-of-cylinders      int64
horsepower            int64
average-mileage       int64
price               float64
dtype: object

In [191]:
df[df['engine-type']=='l']

index    company body-style  wheel-base  length engine-type  \
13     16  chevrolet  hatchback        88.4   141.1           l   

    num-of-cylinders  horsepower  average-mileage   price  
13                 3          48               47  5151.0

In [193]:
df['engine-type']=df['engine-type'].replace('dohc','IVTEC')

In [195]:
df['engine-type'].unique()

array(['IVTEC', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'],
      dtype=object)