## Python Modules

**NumPy**
- Modules are the pre-defined files that contain the python codes which depict the basic functionalities of class, methods, variables etc.
- library and modules names are interchangably used
- The most important object defined in NumPy is an N-dimensional array type called *ndarray*. It describes the collection of items of the same type.
- Each item in an ndarray takes the same size of block in the memory.
- Each element in ndarray is an object of data-type object also called as *dtype*


In [3]:
import numpy as np

In [5]:
arr = np.array([1,2,3])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3])

In [7]:
arr*2

array([2, 4, 6])

In [9]:
arr+10

array([11, 12, 13])

In [11]:
arr

array([1, 2, 3])

In [13]:
arr-9

array([-8, -7, -6])

**2D Array**
- its a combination of 1D array

In [16]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [18]:
a.shape

(2, 2)

In [20]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b.shape

(2, 3)

In [24]:
b+10

array([[11, 12, 13],
       [14, 15, 16]])

In [26]:
c=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
c.shape

(3, 5)

**3D Array**
- its a combination of 2D array
- (layers,rows,columns)

![](3darray.jpg)

In [30]:
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
d.shape

(2, 2, 3)

In [32]:
e=np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
e

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [34]:
e.shape

(4, 3, 2)

In [36]:
f=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
f

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

**Array inspection**
- ndarray.shape - this returns the shape of array
- ndarray.ndim - this returns the dimensionality of array
- ndarray.size - this returns the total no.of elements in array
- ndarray.dtype - this returns the datatype of elements in array
- ndarray.astype - this is used to convert into other data type

In [39]:
f.shape

(2, 2, 5)

In [41]:
f.ndim

3

In [42]:
e.ndim

3

In [43]:
f.size

20

In [44]:
e.size

24

In [49]:
g=np.array([[1,2.1],[4,2.4]])
g.dtype

dtype('float64')

In [50]:
f.dtype

dtype('int32')

In [53]:
e.dtype

dtype('int32')

In [55]:
h=f.astype('float')
h

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]],

       [[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]]])

In [57]:
i=g.astype('int')
i

array([[1, 2],
       [4, 2]])

**Different ways of creating an ndarray**

**empty method**
- for generating random arrays

In [19]:
np.empty([4,3])

array([[8.39460947e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.33511290e-306, 2.02341188e-052],
       [2.65368607e-032, 9.15153508e-071, 1.41531827e-076],
       [4.17823978e-062, 4.19331977e+175, 1.79658106e-052]])

In [43]:
np.empty([4,4], dtype=float)

array([[4.67296746e-307, 1.69121096e-306, 1.89143501e-307,
        3.33772792e-307],
       [6.23042750e-307, 2.22522597e-306, 1.33511969e-306,
        1.37962320e-306],
       [9.34604358e-307, 9.79101082e-307, 1.78020576e-306,
        1.69119873e-306],
       [2.22522868e-306, 1.24611809e-306, 8.06632139e-308,
        1.60221208e-306]])

**Initialized with zeros**

In [45]:
np.zeros([3,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**Initialization with ones**
- default dtype is float unless specified

In [84]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.ones([2,3,4], dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

**Array from numerical ranges**

In [5]:
#arange is array range
q=np.arange(5)
q

array([0, 1, 2, 3, 4])

In [94]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [98]:
np.arange(3,18,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17])

**linspace**
- to get the number of evenly spaced values between intervals
- Parameters for the function(start, stop, num, endpoint,retstep,dtype)
- dtype is that of output array (default is float)

In [103]:
np.linspace(10,20,9)

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [118]:
np.linspace(10,20,9, endpoint=False)
#by default endpoint(i.e., stop value) is included, only when it is set to False it is not included

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889])

In [124]:
np.linspace(10,20,9, endpoint=False, retstep=True)
#if we want to print step size use retstep=True, bydefault it is False)

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889]),
 1.1111111111111112)

In [128]:
np.linspace(10,20,7, endpoint=False, retstep=True, dtype=int)
#If we use dtype int, sometimes it can return evenly spaced, in that case it will roundoff to nearest integer

(array([10, 11, 12, 14, 15, 17, 18]), 1.4285714285714286)

**Generate 20 equally spaced numbers from 100 to 120**

In [141]:
l=np.linspace(100,120,25)
l

array([100.        , 100.83333333, 101.66666667, 102.5       ,
       103.33333333, 104.16666667, 105.        , 105.83333333,
       106.66666667, 107.5       , 108.33333333, 109.16666667,
       110.        , 110.83333333, 111.66666667, 112.5       ,
       113.33333333, 114.16666667, 115.        , 115.83333333,
       116.66666667, 117.5       , 118.33333333, 119.16666667,
       120.        ])

In [137]:
l.size

25

**Array from random numbers**

In [65]:
np.random.rand(4,3)

array([[0.71246768, 0.15696417, 0.45498095],
       [0.02451823, 0.03958697, 0.77079291],
       [0.96064996, 0.03653244, 0.4756915 ],
       [0.23098574, 0.22825599, 0.76448571]])

In [77]:
np.random.randint(1,9,[2,2,2])

array([[[2, 3],
        [4, 8]],

       [[2, 8],
        [2, 4]]])

**Array from full**

In [81]:
np.full([2,3,2],100)

array([[[100, 100],
        [100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100],
        [100, 100]]])

In [85]:
#we can also generate the same using ones
np.ones([2,3,2],dtype=int)*11

array([[[11, 11],
        [11, 11],
        [11, 11]],

       [[11, 11],
        [11, 11],
        [11, 11]]])

**Array from Identity method**

In [168]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**Index and slicing methods**
- Contents of ndarray object can be accessed and modified by indexing and slicing.
- slicing means retriving elements from one index to another index
- slicing includes starting index but excludes the ending index

In [177]:
#Slicing 1D arrays
x=np.arange(2,10)
print(x)

[2 3 4 5 6 7 8 9]


In [179]:
x[5]

7

In [181]:
x[2:5]

array([4, 5, 6])

In [183]:
x[1:6:2]

array([3, 5, 7])