**Slicing 2D array**
- before , it represents about rows and after , it represents about columns
- other things are same as regular slicing

In [6]:
import numpy as np

In [6]:
x=np.array([[1,2,3],[4,5,6]])
x[0]

array([1, 2, 3])

In [8]:
x[0,2]

3

In [14]:
x[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
x[0:2,0]

array([1, 4])

In [12]:
x[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [16]:
x[1:3,1:2]

array([[5]])

In [19]:
x[0,1:3]

array([2, 3])

In [22]:
arr=np.array([[2,3,4,5,6],[8,2,3,10,11],[15,14,1,9,20],[25,24,12,16,26]])
arr

array([[ 2,  3,  4,  5,  6],
       [ 8,  2,  3, 10, 11],
       [15, 14,  1,  9, 20],
       [25, 24, 12, 16, 26]])

In [24]:
arr[2,2]

1

In [26]:
arr[:2,:2]

array([[2, 3],
       [8, 2]])

In [30]:
arr[1:,3:]

array([[10, 11],
       [ 9, 20],
       [16, 26]])

In [32]:
arr[1:3,1:4]

array([[ 2,  3, 10],
       [14,  1,  9]])

In [34]:
arr[:2,1:4]

array([[ 3,  4,  5],
       [ 2,  3, 10]])

In [8]:
y=np.array([[[1,2],[3,4],[5,6]],
          [[7,8],[9,10],[11,12]],
          [[13,14],[15,16],[17,18]]])
y

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [38]:
y.shape

(3, 3, 2)

In [40]:
y[1:3,1:3]

array([[[ 9, 10],
        [11, 12]],

       [[15, 16],
        [17, 18]]])

In [14]:
y[0:3,0:3,1:]

array([[[ 2],
        [ 4],
        [ 6]],

       [[ 8],
        [10],
        [12]],

       [[14],
        [16],
        [18]]])

In [46]:
a=np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[8,9,6,3],[5,6,1,2]],
    [[8,2,5,6],[1,2,3,4]]
])
a

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 9, 6, 3],
        [5, 6, 1, 2]],

       [[8, 2, 5, 6],
        [1, 2, 3, 4]]])

In [54]:
a[:,1:]

array([[[5, 6, 7, 8]],

       [[5, 6, 1, 2]],

       [[1, 2, 3, 4]]])

In [56]:
a[:,1:,2:]

array([[[7, 8]],

       [[1, 2]],

       [[3, 4]]])

In [58]:
a[:,0,2:]

array([[3, 4],
       [6, 3],
       [5, 6]])

In [60]:
 a[:,:,2:]

array([[[3, 4],
        [7, 8]],

       [[6, 3],
        [1, 2]],

       [[5, 6],
        [3, 4]]])

In [66]:
a[1:,:,:2]

array([[[8, 9],
        [5, 6]],

       [[8, 2],
        [1, 2]]])

In [64]:
a[1:,1,:2]

array([[5, 6],
       [1, 2]])

In [68]:
a[1,:,1:3]

array([[9, 6],
       [6, 1]])

In [70]:
a[1:,0,1]

array([9, 2])

In [72]:
a[:2,1,1]

array([6, 6])

**Array Manipulation**  

**np.transpose(array)**
- to transpose array
- it is an operator which flips a matrix over its diagonal
- that is it switches rows and columns indices of the matrix
  

In [105]:
#2d array
e=np.array([[2,3,4,5,6],[8,2,3,10,11],[15,14,1,9,20],[25,24,12,16,26]])
e

array([[ 2,  3,  4,  5,  6],
       [ 8,  2,  3, 10, 11],
       [15, 14,  1,  9, 20],
       [25, 24, 12, 16, 26]])

In [107]:
e.shape

(4, 5)

In [109]:
#transposing 2d array
f=np.transpose(e)
f

array([[ 2,  8, 15, 25],
       [ 3,  2, 14, 24],
       [ 4,  3,  1, 12],
       [ 5, 10,  9, 16],
       [ 6, 11, 20, 26]])

In [111]:
f.shape

(5, 4)

In [113]:
#3d array
c=np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[8,9,6,3],[5,6,1,2]],
    [[8,2,5,6],[1,2,3,4]]
])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 9, 6, 3],
        [5, 6, 1, 2]],

       [[8, 2, 5, 6],
        [1, 2, 3, 4]]])

In [115]:
c.shape

(3, 2, 4)

In [117]:
#transposing 3d array
d=np.transpose(c)
d

array([[[1, 8, 8],
        [5, 5, 1]],

       [[2, 9, 2],
        [6, 6, 2]],

       [[3, 6, 5],
        [7, 1, 3]],

       [[4, 3, 6],
        [8, 2, 4]]])

In [119]:
d.shape

(4, 2, 3)

**reshape(shape)**
- gives a new shape to the array without changing its data
- data cannot be modified

In [132]:
d=np.arange(1,7)
d

array([1, 2, 3, 4, 5, 6])

In [134]:
d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [136]:
d.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

**np.resize(array,shape)**
- changes the shape and size of array in-place
- data maybe same or not

In [143]:
d

array([1, 2, 3, 4, 5, 6])

In [147]:
shape=(2,7)
np.resize(d,shape)

array([[1, 2, 3, 4, 5, 6, 1],
       [2, 3, 4, 5, 6, 1, 2]])

In [152]:
np.resize(d,(2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [1, 2]]])

**flatten()**
- returns flattened 1D arrays

In [156]:
c=np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[8,9,6,3],[5,6,1,2]],
    [[8,2,5,6],[1,2,3,4]]
])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 9, 6, 3],
        [5, 6, 1, 2]],

       [[8, 2, 5, 6],
        [1, 2, 3, 4]]])

In [158]:
c.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 6, 3, 5, 6, 1, 2, 8, 2, 5, 6, 1, 2,
       3, 4])

In [160]:
e=np.array([[2,3,4,5,6],[8,2,3,10,11],[15,14,1,9,20],[25,24,12,16,26]])
e

array([[ 2,  3,  4,  5,  6],
       [ 8,  2,  3, 10, 11],
       [15, 14,  1,  9, 20],
       [25, 24, 12, 16, 26]])

In [162]:
e.flatten()

array([ 2,  3,  4,  5,  6,  8,  2,  3, 10, 11, 15, 14,  1,  9, 20, 25, 24,
       12, 16, 26])