In [1]:
import numpy as np
from numpy import random as r

In [2]:
nums = r.randint(0,50,size=10)
nums

array([47, 43, 28,  3,  9, 13, 30, 13, 17, 43])

In [3]:
res = list(filter(lambda num: num>=20,nums))
res

[47, 43, 28, 30, 43]

In [4]:
boolRes=nums>=20
print(nums[boolRes])

[47 43 28 30 43]


In [5]:
names=['aa','b','c','d','e']
scores=[1,2,33,332,423]

index=np.argmax(scores)
# index
print(names[index])

e


In [6]:
a=list(range(1,10))
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
marks=[[1,2],[4,5]]
print(sum(marks))

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [11]:
total = 0
for mark in marks:
    total+=sum(mark)
print(total)

12


In [13]:
list1=np.array([[12,15,19],
                [23,4234,231],
                [24,234,545],
                [4234,243,465]])
print(list1)

print(list1[1:3,:2])

[[  12   15   19]
 [  23 4234  231]
 [  24  234  545]
 [4234  243  465]]
[[  23 4234]
 [  24  234]]


In [15]:
list2=[[12,15,19],
        [23,4234,231],
        [24,234,545],
        [4234,243,465]]

print(list2[1:3][1:3])

[[24, 234, 545]]


In [17]:
updated=list1+[2,0,5]
print(updated)

[[  14   15   24]
 [  25 4234  236]
 [  26  234  550]
 [4236  243  470]]


In [19]:
np_mat1=np.array([[1,4,3],[3,9,5]])
np_mat2=np.array([[4,2,8],[2,9,3]])
np_mat3=np.array([[4,2],[2,9],[8,3]])

np_mul1=np_mat1*np_mat2
print(np_mul1)

np_mul2=np_mat1@np_mat3
print(np_mul2)

[[ 4  8 24]
 [ 6 81 15]]
[[ 36  47]
 [ 70 102]]


In [21]:
print(sum(list2))

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [23]:
np_arr=np.array(list2)
print(np_arr.sum())
print(np.sum(np_arr))

10279
10279


In [25]:
print(list1.sum(axis=0)) #column wise

[4293 4726 1260]


In [28]:
import pandas as pd

In [30]:
scores

[1, 2, 33, 332, 423]

In [32]:
ps_scores=pd.Series(scores)

In [35]:
ps_scores

0      1
1      2
2     33
3    332
4    423
dtype: int64

In [37]:
ps_scores[1]

2

In [39]:
ps_scores[-1]

KeyError: -1

In [41]:
stud_names=['a','b','c','d','e']

In [43]:
studMarks=pd.Series(scores, index=stud_names)
print(studMarks)

a      1
b      2
c     33
d    332
e    423
dtype: int64


In [45]:
studMarks[1]

C:\Users\PHANEENDRA\AppData\Local\Temp\ipykernel_18140\1754870549.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  studMarks[1]


2

In [49]:
studMarks['a']

1

In [51]:
studMarks[-1]

C:\Users\PHANEENDRA\AppData\Local\Temp\ipykernel_18140\142218215.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  studMarks[-1]


423

In [65]:
stud_index=[8,9,10,11,11]

In [67]:
studScores=pd.Series(scores, index=stud_index)
print(studScores)

8       1
9       2
10     33
11    332
11    423
dtype: int64


In [69]:
print(studScores[11])

11    332
11    423
dtype: int64


In [61]:
print(studScores.iloc[2])

33


In [85]:
winners={1975:'WI',1979:'WI',1983:'IND',1987:'AUS',1992:'PK',1996:'SL',1999:'AUS',2003:'AUS',2007:'AUS',2011:'IND',2015:'AUS',2019:'ENG'}
world_cup=pd.Series(winners)
print(world_cup.unique())
print(world_cup.value_counts())

['WI' 'IND' 'AUS' 'PK' 'SL' 'ENG']
AUS    5
WI     2
IND    2
PK     1
SL     1
ENG    1
Name: count, dtype: int64


In [91]:
studScores

8       1
9       2
10     33
11    332
11    423
dtype: int64

In [105]:
sq_numbers=studScores.apply(lambda studScores:studScores**2)
print(sq_numbers)

8          1
9          4
10      1089
11    110224
11    178929
dtype: int64
